/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.112
 * Generated at: 2025-12-12 16:03:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.railway.model.User;

public final class admin_002ddashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.railway.model.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    User user = (User) session.getAttribute("user");
    if (user == null || !"ADMIN".equals(user.getRole())) {
        response.sendRedirect("login.jsp");
        return;
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Admin Dashboard - Railway Reservation</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        * { margin: 0; padding: 0; box-sizing: border-box; }\r\n");
      out.write("        body { font-family: Arial, sans-serif; background: #f7fafc; }\r\n");
      out.write("        \r\n");
      out.write("        .navbar { background: #2d3748; color: white; padding: 15px 30px; display: flex; justify-content: space-between; align-items: center; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }\r\n");
      out.write("        .navbar h1 { font-size: 22px; }\r\n");
      out.write("        .navbar a { color: white; text-decoration: none; margin-left: 20px; padding: 8px 15px; border-radius: 5px; transition: 0.3s; font-weight: bold; }\r\n");
      out.write("        .navbar a:hover { background: rgba(255,255,255,0.2); }\r\n");
      out.write("        \r\n");
      out.write("        .container { max-width: 1200px; margin: 30px auto; padding: 0 20px; }\r\n");
      out.write("        \r\n");
      out.write("        .welcome { background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); margin-bottom: 30px; border-left: 5px solid #2d3748; }\r\n");
      out.write("        .welcome h2 { color: #333; margin-bottom: 10px; }\r\n");
      out.write("        \r\n");
      out.write("        .admin-badge { background: #f6ad55; color: white; padding: 5px 15px; border-radius: 20px; display: inline-block; margin-left: 10px; font-size: 14px; font-weight: bold; }\r\n");
      out.write("        \r\n");
      out.write("        .user-info { background: #fff5e6; padding: 20px; border-radius: 5px; margin-top: 15px; border-left: 4px solid #f6ad55; }\r\n");
      out.write("        .user-info p { margin: 8px 0; color: #555; }\r\n");
      out.write("        \r\n");
      out.write("        .cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 20px; margin-top: 30px; }\r\n");
      out.write("        \r\n");
      out.write("        /* 🛠️ MODIFIED CARD CSS TO MAKE IT CLICKABLE */\r\n");
      out.write("        .card { \r\n");
      out.write("            display: block; /* Makes the link behave like a box */\r\n");
      out.write("            text-decoration: none; /* Removes the underline */\r\n");
      out.write("            background: white; \r\n");
      out.write("            padding: 25px; \r\n");
      out.write("            border-radius: 10px; \r\n");
      out.write("            box-shadow: 0 2px 10px rgba(0,0,0,0.1); \r\n");
      out.write("            text-align: center; \r\n");
      out.write("            transition: 0.3s; \r\n");
      out.write("            color: inherit; /* Keeps text color normal */\r\n");
      out.write("            border-top: 5px solid #cbd5e0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .card:hover { transform: translateY(-5px); box-shadow: 0 5px 20px rgba(0,0,0,0.15); }\r\n");
      out.write("        .card h3 { color: #667eea; margin-bottom: 10px; font-size: 18px; }\r\n");
      out.write("        .card p { color: #666; margin-bottom: 15px; font-size: 14px; }\r\n");
      out.write("        .card .icon { font-size: 40px; margin-bottom: 10px; }\r\n");
      out.write("\r\n");
      out.write("        /* Specific Colors for buttons */\r\n");
      out.write("        .card-green { border-top-color: #48bb78; }\r\n");
      out.write("        .card-blue { border-top-color: #4299e1; }\r\n");
      out.write("        .card-orange { border-top-color: #ed8936; }\r\n");
      out.write("        .card-red { border-top-color: #e53e3e; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"navbar\">\r\n");
      out.write("        <h1>🚂 Admin Control Panel</h1>\r\n");
      out.write("        <div>\r\n");
      out.write("            <span>👤 ");
      out.print( user.getFullName() );
      out.write("</span>\r\n");
      out.write("            <a href=\"LogoutServlet\">Logout</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"welcome\">\r\n");
      out.write("            <h2>Welcome, ");
      out.print( user.getFullName() );
      out.write("! 👋 <span class=\"admin-badge\">ADMIN</span></h2>\r\n");
      out.write("            <p>You have administrator access to the Railway Reservation System</p>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"user-info\">\r\n");
      out.write("                <p><strong>👤 Username:</strong> ");
      out.print( user.getUsername() );
      out.write("</p>\r\n");
      out.write("                <p><strong>📧 Email:</strong> ");
      out.print( user.getEmail() );
      out.write("</p>\r\n");
      out.write("                <p><strong>🔑 Role:</strong> ");
      out.print( user.getRole() );
      out.write("</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"cards\">\r\n");
      out.write("            \r\n");
      out.write("            <a href=\"add-train.jsp\" class=\"card card-green\">\r\n");
      out.write("                <div class=\"icon\">➕</div>\r\n");
      out.write("                <h3>Add New Train</h3>\r\n");
      out.write("                <p>Create new trains, set routes, and prices</p>\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <a href=\"ManageTrainServlet\" class=\"card card-blue\">\r\n");
      out.write("                <div class=\"icon\">🚊</div>\r\n");
      out.write("                <h3>Manage Trains</h3>\r\n");
      out.write("                <p>Update or remove train schedules</p>\r\n");
      out.write("            </a>\r\n");
      out.write("            \r\n");
      out.write("            <a href=\"AllBookingsServlet\" class=\"card card-orange\">\r\n");
      out.write("                <div class=\"icon\">🎫</div>\r\n");
      out.write("                <h3>All Bookings</h3>\r\n");
      out.write("                <p>View and manage all reservations</p>\r\n");
      out.write("            </a>\r\n");
      out.write("            \r\n");
      out.write("            <a href=\"LogoutServlet\" class=\"card card-red\">\r\n");
      out.write("                <div class=\"icon\">🚪</div>\r\n");
      out.write("                <h3>Logout</h3>\r\n");
      out.write("                <p>Sign out of the admin panel</p>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
