/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.112
 * Generated at: 2025-12-08 20:14:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.railway.model.Reservation;

public final class booking_002dsuccess_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.railway.model.Reservation");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    // Get the reservation object sent by the Servlet
    Reservation res = (Reservation) request.getAttribute("reservation");
    
    // Safety check: If someone tries to open this page directly without booking, send them home
    if(res == null) { 
        response.sendRedirect("user-dashboard.jsp"); 
        return; 
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Booking Confirmed - Railway System</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body { font-family: 'Courier New', Courier, monospace; background: #e2e8f0; display: flex; justify-content: center; padding-top: 50px; }\r\n");
      out.write("        .ticket { background: white; width: 600px; padding: 20px; border-left: 10px solid #48bb78; border-right: 10px dotted #48bb78; box-shadow: 0 10px 25px rgba(0,0,0,0.1); }\r\n");
      out.write("        .header { text-align: center; border-bottom: 2px dashed #cbd5e0; padding-bottom: 10px; margin-bottom: 20px; }\r\n");
      out.write("        .header h2 { color: #2d3748; margin: 0; }\r\n");
      out.write("        .success-msg { color: #48bb78; font-weight: bold; font-size: 18px; }\r\n");
      out.write("        .row { display: flex; justify-content: space-between; margin-bottom: 15px; }\r\n");
      out.write("        .label { color: #718096; font-size: 14px; font-weight: bold; }\r\n");
      out.write("        .value { color: #2d3748; font-size: 16px; font-weight: bold; }\r\n");
      out.write("        .total-price { background: #f0fff4; padding: 15px; text-align: center; border: 2px dashed #48bb78; font-size: 24px; font-weight: bold; color: #2f855a; margin-top: 20px; }\r\n");
      out.write("        .btn-home { display: block; text-align: center; margin-top: 20px; text-decoration: none; color: #4299e1; font-weight: bold; font-family: Arial, sans-serif; padding: 10px; border: 1px solid #4299e1; border-radius: 5px; }\r\n");
      out.write("        .btn-home:hover { background: #ebf8ff; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"ticket\">\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("            <h2>🚂 RAILWAY TICKET</h2>\r\n");
      out.write("            <p class=\"success-msg\">✅ Booking Confirmed</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <span class=\"label\">PASSENGER NAME</span><br>\r\n");
      out.write("                <span class=\"value\">");
      out.print( res.getPassengerName() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <span class=\"label\">AGE / GENDER</span><br>\r\n");
      out.write("                <span class=\"value\">");
      out.print( res.getAge() );
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.print( res.getGender() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <span class=\"label\">JOURNEY DATE</span><br>\r\n");
      out.write("                <span class=\"value\">");
      out.print( res.getJourneyDate() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <span class=\"label\">SEATS BOOKED</span><br>\r\n");
      out.write("                <span class=\"value\">");
      out.print( res.getSeatsBooked() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("             <div>\r\n");
      out.write("                <span class=\"label\">STATUS</span><br>\r\n");
      out.write("                <span class=\"value\" style=\"color: green;\">CONFIRMED</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"total-price\">\r\n");
      out.write("            TOTAL PAID: ₹");
      out.print( res.getTotalFare() );
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"user-dashboard.jsp\" class=\"btn-home\">🏠 Return to Dashboard</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
