/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.112
 * Generated at: 2025-12-09 14:51:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.railway.dao.TrainDAO;
import com.railway.model.Train;
import com.railway.model.User;
import com.railway.model.User;

public final class book_002dticket_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1765286761597L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.railway.model.User");
    _jspx_imports_classes.add("com.railway.dao.TrainDAO");
    _jspx_imports_classes.add("com.railway.model.Train");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    User user = (User) session.getAttribute("user");
    if(user == null) { response.sendRedirect("login.jsp"); return; }

    // Get Data from URL
    String trainIdStr = request.getParameter("trainId");
    String date = request.getParameter("date");
    String trainClass = request.getParameter("trainClass"); 
    String distance = request.getParameter("distance");
    String searchSource = request.getParameter("source");
    String searchDest = request.getParameter("destination");
    
    TrainDAO dao = new TrainDAO();
    Train train = dao.getTrainById(Integer.parseInt(trainIdStr));

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Book Ticket</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body { font-family: 'Segoe UI', sans-serif; background: #f7fafc; margin:0; }\r\n");
      out.write("        .container { max-width: 600px; margin: 40px auto; background: white; padding: 40px; border-radius: 10px; box-shadow: 0 5px 15px rgba(0,0,0,0.1); }\r\n");
      out.write("        .info-box { background: #ebf8ff; padding: 15px; border-radius: 5px; margin-bottom: 20px; border-left: 5px solid #4299e1; }\r\n");
      out.write("        label { display: block; font-weight: bold; margin-top: 15px; color: #4a5568; }\r\n");
      out.write("        input, select { width: 100%; padding: 10px; margin-top: 5px; border: 1px solid #cbd5e0; border-radius: 5px; }\r\n");
      out.write("        .price-display { background: #f0fff4; color: #276749; padding: 15px; font-size: 20px; font-weight: bold; text-align: center; margin-top: 20px; border: 2px dashed #48bb78; border-radius: 10px; }\r\n");
      out.write("        .btn-pay { width: 100%; padding: 15px; background: #48bb78; color: white; border: none; font-size: 18px; font-weight: bold; border-radius: 5px; margin-top: 10px; cursor: pointer; }\r\n");
      out.write("        .btn-pay:hover { background: #38a169; }\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("        // 🧠 JS Logic to Show Price Instantly (Matches your Servlet Logic)\r\n");
      out.write("        function calculateLivePrice() {\r\n");
      out.write("            var distance = ");
      out.print( distance );
      out.write(";\r\n");
      out.write("            var trainClass = \"");
      out.print( trainClass );
      out.write("\";\r\n");
      out.write("            var seats = document.getElementById(\"seats\").value;\r\n");
      out.write("            var pricePerTicket = 0;\r\n");
      out.write("\r\n");
      out.write("            // Short Distance Logic\r\n");
      out.write("            if (distance <= 20) pricePerTicket = 10;\r\n");
      out.write("            else if (distance <= 50) pricePerTicket = 20;\r\n");
      out.write("            else if (distance <= 100 && trainClass === \"GN\") pricePerTicket = 30;\r\n");
      out.write("            else {\r\n");
      out.write("                // Long Distance Logic\r\n");
      out.write("                var rate = 0.4;\r\n");
      out.write("                if (trainClass === \"SL\") rate = 0.8;\r\n");
      out.write("                if (trainClass === \"3AC\") rate = 1.5;\r\n");
      out.write("                if (trainClass === \"2AC\") rate = 2.5;\r\n");
      out.write("                if (trainClass === \"1AC\") rate = 3.5;\r\n");
      out.write("                pricePerTicket = distance * rate;\r\n");
      out.write("                \r\n");
      out.write("                // Min Fares\r\n");
      out.write("                if (trainClass === \"1AC\" && pricePerTicket < 1000) pricePerTicket = 1000;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            var total = Math.round(pricePerTicket * seats);\r\n");
      out.write("            document.getElementById(\"totalPrice\").innerText = \"₹\" + total;\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"calculateLivePrice()\">\r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");

    User navUser = (User) session.getAttribute("user");

      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    /* Navbar Styling */\r\n");
      out.write("    .navbar { background: linear-gradient(90deg, #667eea, #764ba2); color: white; padding: 10px 30px; display: flex; justify-content: space-between; align-items: center; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }\r\n");
      out.write("    .logo { font-size: 22px; font-weight: bold; text-decoration: none; color: white; display: flex; align-items: center; gap: 10px; }\r\n");
      out.write("    \r\n");
      out.write("    /* Profile Dropdown */\r\n");
      out.write("    .profile-menu { position: relative; display: inline-block; cursor: pointer; }\r\n");
      out.write("    .profile-btn { background: rgba(255,255,255,0.2); padding: 8px 15px; border-radius: 20px; font-weight: bold; display: flex; align-items: center; gap: 8px; transition: 0.3s; }\r\n");
      out.write("    .profile-btn:hover { background: rgba(255,255,255,0.3); }\r\n");
      out.write("    \r\n");
      out.write("    /* Dropdown Content (Hidden by Default) */\r\n");
      out.write("    .dropdown-content { display: none; position: absolute; right: 0; background-color: white; min-width: 200px; box-shadow: 0 8px 16px rgba(0,0,0,0.2); border-radius: 8px; z-index: 1000; overflow: hidden; margin-top: 10px; }\r\n");
      out.write("    .dropdown-content p { color: #2d3748; padding: 12px 16px; margin: 0; border-bottom: 1px solid #edf2f7; font-size: 14px; }\r\n");
      out.write("    .dropdown-content a { color: #e53e3e; padding: 12px 16px; text-decoration: none; display: block; font-weight: bold; }\r\n");
      out.write("    .dropdown-content a:hover { background-color: #f7fafc; }\r\n");
      out.write("\r\n");
      out.write("    /* Show Dropdown on Hover */\r\n");
      out.write("    .profile-menu:hover .dropdown-content { display: block; }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class=\"navbar\">\r\n");
      out.write("    <a href=\"user-dashboard.jsp\" class=\"logo\">🚂 Railway System</a>\r\n");
      out.write("    \r\n");
      out.write("    ");
 if (navUser != null) { 
      out.write("\r\n");
      out.write("        <div class=\"profile-menu\">\r\n");
      out.write("            <div class=\"profile-btn\">\r\n");
      out.write("                👤 ");
      out.print( navUser.getFullName() );
      out.write(" ▼\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"dropdown-content\">\r\n");
      out.write("                <p><strong>User:</strong> ");
      out.print( navUser.getUsername() );
      out.write("</p>\r\n");
      out.write("                <p><strong>Email:</strong> ");
      out.print( navUser.getEmail() );
      out.write("</p>\r\n");
      out.write("                <p><strong>Phone:</strong> ");
      out.print( navUser.getPhone() );
      out.write("</p>\r\n");
      out.write("                <a href=\"LogoutServlet\">🚪 Logout</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h2 style=\"text-align: center;\">Confirm Booking</h2>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"info-box\">\r\n");
      out.write("            <p><strong>Train:</strong> ");
      out.print( train.getTrainName() );
      out.write(' ');
      out.write('(');
      out.print( train.getTrainNumber() );
      out.write(")</p>\r\n");
      out.write("            <p><strong>Route:</strong> ");
      out.print( searchSource );
      out.write(' ');
      out.write('➝');
      out.write(' ');
      out.print( searchDest );
      out.write(' ');
      out.write('(');
      out.print( distance );
      out.write(" km)</p>\r\n");
      out.write("            <p><strong>Date:</strong> ");
      out.print( date );
      out.write(" | <strong>Class:</strong> ");
      out.print( trainClass );
      out.write("</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <form action=\"BookingServlet\" method=\"post\">\r\n");
      out.write("            <input type=\"hidden\" name=\"trainId\" value=\"");
      out.print( train.getTrainId() );
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"date\" value=\"");
      out.print( date );
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"source\" value=\"");
      out.print( searchSource );
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"destination\" value=\"");
      out.print( searchDest );
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"trainClass\" value=\"");
      out.print( trainClass );
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"distance\" value=\"");
      out.print( distance );
      out.write("\">\r\n");
      out.write("            \r\n");
      out.write("            <label>Passenger Name</label>\r\n");
      out.write("            <input type=\"text\" name=\"passengerName\" required>\r\n");
      out.write("            \r\n");
      out.write("            <label>Age</label>\r\n");
      out.write("            <input type=\"number\" name=\"age\" required>\r\n");
      out.write("            \r\n");
      out.write("            <label>Gender</label>\r\n");
      out.write("            <select name=\"gender\">\r\n");
      out.write("                <option>Male</option> <option>Female</option> <option>Other</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            \r\n");
      out.write("            <label>Seats</label>\r\n");
      out.write("            <input type=\"number\" id=\"seats\" name=\"seats\" value=\"1\" min=\"1\" max=\"6\" oninput=\"calculateLivePrice()\" required>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"price-display\">\r\n");
      out.write("                Total Pay: <span id=\"totalPrice\">Calculating...</span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <button type=\"submit\" class=\"btn-pay\">Pay & Book</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
