/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.112
 * Generated at: 2025-12-12 18:34:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.railway.model.Train;
import com.railway.model.User;

public final class manage_002dtrains_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1765564101043L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.railway.model.User");
    _jspx_imports_classes.add("com.railway.model.Train");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    // 1. SECURITY: Prevent Back Button after Logout
    response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate"); // HTTP 1.1
    response.setHeader("Pragma", "no-cache"); // HTTP 1.0
    response.setDateHeader("Expires", 0); // Proxies

    // 2. GET USER
    User navUser = (User) session.getAttribute("user");

      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    /* Navbar Styling */\r\n");
      out.write("    .navbar { background: linear-gradient(90deg, #667eea, #764ba2); color: white; padding: 10px 30px; display: flex; justify-content: space-between; align-items: center; box-shadow: 0 4px 6px rgba(0,0,0,0.1); font-family: 'Segoe UI', sans-serif; }\r\n");
      out.write("    .logo { font-size: 22px; font-weight: bold; text-decoration: none; color: white; display: flex; align-items: center; gap: 10px; }\r\n");
      out.write("    \r\n");
      out.write("    /* Profile Dropdown */\r\n");
      out.write("    .profile-menu { position: relative; display: inline-block; cursor: pointer; }\r\n");
      out.write("    .profile-btn { background: rgba(255,255,255,0.2); padding: 8px 15px; border-radius: 20px; font-weight: bold; display: flex; align-items: center; gap: 8px; transition: 0.3s; }\r\n");
      out.write("    .profile-btn:hover { background: rgba(255,255,255,0.3); }\r\n");
      out.write("    \r\n");
      out.write("    /* Dropdown Content */\r\n");
      out.write("    .dropdown-content { display: none; position: absolute; right: 0; background-color: white; min-width: 200px; box-shadow: 0 8px 16px rgba(0,0,0,0.2); border-radius: 8px; z-index: 1000; overflow: hidden; margin-top: 10px; }\r\n");
      out.write("    .dropdown-content p { color: #2d3748; padding: 12px 16px; margin: 0; border-bottom: 1px solid #edf2f7; font-size: 14px; }\r\n");
      out.write("    .dropdown-content a { color: #e53e3e; padding: 12px 16px; text-decoration: none; display: block; font-weight: bold; }\r\n");
      out.write("    .dropdown-content a:hover { background-color: #f7fafc; }\r\n");
      out.write("\r\n");
      out.write("    /* Show Dropdown on Hover */\r\n");
      out.write("    .profile-menu:hover .dropdown-content { display: block; }\r\n");
      out.write("    \r\n");
      out.write("    /* Admin Badge Style */\r\n");
      out.write("    .admin-badge { background: #e53e3e; color: white; padding: 2px 8px; border-radius: 4px; font-size: 12px; margin-left: 10px; vertical-align: middle; }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class=\"navbar\">\r\n");
      out.write("    <div style=\"display:flex; align-items:center;\">\r\n");
      out.write("        <a href=\"user-dashboard.jsp\" class=\"logo\">🚂 Railway System</a>\r\n");
      out.write("        \r\n");
      out.write("        ");
 if(navUser != null && "ADMIN".equals(navUser.getRole())) { 
      out.write("\r\n");
      out.write("            <span class=\"admin-badge\">ADMIN MODE</span>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    ");
 if (navUser != null) { 
      out.write("\r\n");
      out.write("        <div class=\"profile-menu\">\r\n");
      out.write("            <div class=\"profile-btn\">\r\n");
      out.write("                👤 ");
      out.print( navUser.getFullName() );
      out.write(" ▼\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"dropdown-content\">\r\n");
      out.write("                <p><strong>User:</strong> ");
      out.print( navUser.getUsername() );
      out.write("</p>\r\n");
      out.write("                <p><strong>Email:</strong> ");
      out.print( navUser.getEmail() );
      out.write("</p>\r\n");
      out.write("                <p><strong>Phone:</strong> ");
      out.print( navUser.getPhone() );
      out.write("</p>\r\n");
      out.write("                <a href=\"LogoutServlet\">🚪 Logout</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Manage Trains</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body { font-family: 'Segoe UI', sans-serif; background: #f7fafc; padding: 20px; }\r\n");
      out.write("        .container { max-width: 1100px; margin: 0 auto; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 5px 15px rgba(0,0,0,0.1); }\r\n");
      out.write("        h2 { text-align: center; color: #2d3748; margin-bottom: 20px; }\r\n");
      out.write("        \r\n");
      out.write("        table { width: 100%; border-collapse: collapse; margin-top: 20px; }\r\n");
      out.write("        th, td { padding: 12px; border-bottom: 1px solid #ddd; text-align: left; }\r\n");
      out.write("        th { background: #667eea; color: white; }\r\n");
      out.write("        tr:hover { background-color: #f1f1f1; }\r\n");
      out.write("        \r\n");
      out.write("        .btn { padding: 5px 10px; text-decoration: none; border-radius: 4px; font-size: 13px; font-weight: bold; }\r\n");
      out.write("        .btn-edit { background: #4299e1; color: white; }\r\n");
      out.write("        .btn-delete { background: #e53e3e; color: white; margin-left: 5px; }\r\n");
      out.write("        .btn-add { display:inline-block; background: #48bb78; color:white; padding: 10px 15px; margin-bottom: 15px; text-decoration:none; border-radius:5px; font-weight:bold;}\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <h2>🚆 Manage Train Schedules</h2>\r\n");
      out.write("        \r\n");
      out.write("        <a href=\"add-train.jsp\" class=\"btn-add\">➕ Add New Train</a>\r\n");
      out.write("        \r\n");
      out.write("        <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>ID</th>\r\n");
      out.write("                <th>Name / Number</th>\r\n");
      out.write("                <th>Route</th>\r\n");
      out.write("                <th>Timings</th>\r\n");
      out.write("                <th>Seats</th>\r\n");
      out.write("                <th>Actions</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");
 
                List<Train> list = (List<Train>) request.getAttribute("trainList");
                if (list != null) {
                    for (Train t : list) {
            
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>");
      out.print( t.getTrainId() );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( t.getTrainName() );
      out.write(" <br> <small style=\"color:grey\">");
      out.print( t.getTrainNumber() );
      out.write("</small></td>\r\n");
      out.write("                <td>");
      out.print( t.getSourceStation() );
      out.write(' ');
      out.write('➝');
      out.write(' ');
      out.print( t.getDestinationStation() );
      out.write("</td>\r\n");
      out.write("                <td>Dep: ");
      out.print( t.getDepartureTime() );
      out.write(" <br> Arr: ");
      out.print( t.getArrivalTime() );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( t.getAvailableSeats() );
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.print( t.getTotalSeats() );
      out.write("</td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <a href=\"ManageRouteServlet?trainId=");
      out.print( t.getTrainId() );
      out.write("\" class=\"btn\" style=\"background:#805ad5; color:white; margin-right:5px;\">📍 Route</a>\r\n");
      out.write("\r\n");
      out.write("                    <a href=\"EditTrainServlet?id=");
      out.print( t.getTrainId() );
      out.write("\" class=\"btn btn-edit\">✏ Edit</a>\r\n");
      out.write("\r\n");
      out.write("                    <a href=\"DeleteTrainServlet?id=");
      out.print( t.getTrainId() );
      out.write("\" onclick=\"return confirm('Delete this train?')\" class=\"btn btn-delete\">🗑</a>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");
 
                    }
                } 
            
      out.write("\r\n");
      out.write("        </table>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
