/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.112
 * Generated at: 2025-12-13 17:11:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.railway.model.Train;
import com.railway.model.StationStop;
import com.railway.model.User;

public final class manage_002droute_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1765564101043L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.railway.model.User");
    _jspx_imports_classes.add("com.railway.model.Train");
    _jspx_imports_classes.add("com.railway.model.StationStop");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    // 1. SECURITY: Prevent Back Button after Logout
    response.setHeader("Cache-Control", "no-cache, no-store, must-revalidate"); // HTTP 1.1
    response.setHeader("Pragma", "no-cache"); // HTTP 1.0
    response.setDateHeader("Expires", 0); // Proxies

    // 2. GET USER
    User navUser = (User) session.getAttribute("user");

      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    /* Navbar Styling */\r\n");
      out.write("    .navbar { background: linear-gradient(90deg, #667eea, #764ba2); color: white; padding: 10px 30px; display: flex; justify-content: space-between; align-items: center; box-shadow: 0 4px 6px rgba(0,0,0,0.1); font-family: 'Segoe UI', sans-serif; }\r\n");
      out.write("    .logo { font-size: 22px; font-weight: bold; text-decoration: none; color: white; display: flex; align-items: center; gap: 10px; }\r\n");
      out.write("    \r\n");
      out.write("    /* Profile Dropdown */\r\n");
      out.write("    .profile-menu { position: relative; display: inline-block; cursor: pointer; }\r\n");
      out.write("    .profile-btn { background: rgba(255,255,255,0.2); padding: 8px 15px; border-radius: 20px; font-weight: bold; display: flex; align-items: center; gap: 8px; transition: 0.3s; }\r\n");
      out.write("    .profile-btn:hover { background: rgba(255,255,255,0.3); }\r\n");
      out.write("    \r\n");
      out.write("    /* Dropdown Content */\r\n");
      out.write("    .dropdown-content { display: none; position: absolute; right: 0; background-color: white; min-width: 200px; box-shadow: 0 8px 16px rgba(0,0,0,0.2); border-radius: 8px; z-index: 1000; overflow: hidden; margin-top: 10px; }\r\n");
      out.write("    .dropdown-content p { color: #2d3748; padding: 12px 16px; margin: 0; border-bottom: 1px solid #edf2f7; font-size: 14px; }\r\n");
      out.write("    .dropdown-content a { color: #e53e3e; padding: 12px 16px; text-decoration: none; display: block; font-weight: bold; }\r\n");
      out.write("    .dropdown-content a:hover { background-color: #f7fafc; }\r\n");
      out.write("\r\n");
      out.write("    /* Show Dropdown on Hover */\r\n");
      out.write("    .profile-menu:hover .dropdown-content { display: block; }\r\n");
      out.write("    \r\n");
      out.write("    /* Admin Badge Style */\r\n");
      out.write("    .admin-badge { background: #e53e3e; color: white; padding: 2px 8px; border-radius: 4px; font-size: 12px; margin-left: 10px; vertical-align: middle; }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div class=\"navbar\">\r\n");
      out.write("    <div style=\"display:flex; align-items:center;\">\r\n");
      out.write("        <a href=\"user-dashboard.jsp\" class=\"logo\">🚂 Railway System</a>\r\n");
      out.write("        \r\n");
      out.write("        ");
 if(navUser != null && "ADMIN".equals(navUser.getRole())) { 
      out.write("\r\n");
      out.write("            <span class=\"admin-badge\">ADMIN MODE</span>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    ");
 if (navUser != null) { 
      out.write("\r\n");
      out.write("        <div class=\"profile-menu\">\r\n");
      out.write("            <div class=\"profile-btn\">\r\n");
      out.write("                👤 ");
      out.print( navUser.getFullName() );
      out.write(" ▼\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"dropdown-content\">\r\n");
      out.write("                <p><strong>User:</strong> ");
      out.print( navUser.getUsername() );
      out.write("</p>\r\n");
      out.write("                <p><strong>Email:</strong> ");
      out.print( navUser.getEmail() );
      out.write("</p>\r\n");
      out.write("                <p><strong>Phone:</strong> ");
      out.print( navUser.getPhone() );
      out.write("</p>\r\n");
      out.write("                <a href=\"LogoutServlet\">🚪 Logout</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("</div>");
      out.write('\r');
      out.write('\n');
 
    Train t = (Train) request.getAttribute("train"); 
    List<StationStop> stops = (List<StationStop>) request.getAttribute("stops");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Manage Route</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body { font-family: 'Segoe UI', sans-serif; background: #f7fafc; padding: 20px; }\r\n");
      out.write("        .container { max-width: 900px; margin: 0 auto; display: grid; grid-template-columns: 2fr 1fr; gap: 20px; }\r\n");
      out.write("        \r\n");
      out.write("        /* Left: Route Table */\r\n");
      out.write("        .route-box { background: white; padding: 20px; border-radius: 10px; box-shadow: 0 4px 10px rgba(0,0,0,0.1); }\r\n");
      out.write("        h2 { color: #2d3748; margin-top: 0; }\r\n");
      out.write("        table { width: 100%; border-collapse: collapse; margin-top: 10px; }\r\n");
      out.write("        th, td { padding: 10px; border-bottom: 1px solid #eee; text-align: left; }\r\n");
      out.write("        th { background: #667eea; color: white; }\r\n");
      out.write("        \r\n");
      out.write("        /* Right: Add Form */\r\n");
      out.write("        .add-box { background: white; padding: 20px; border-radius: 10px; box-shadow: 0 4px 10px rgba(0,0,0,0.1); height: fit-content; border-top: 5px solid #48bb78; }\r\n");
      out.write("        input { width: 100%; padding: 10px; margin-bottom: 10px; border: 1px solid #ddd; border-radius: 5px; box-sizing: border-box; }\r\n");
      out.write("        .btn-add { width: 100%; padding: 10px; background: #48bb78; color: white; border: none; font-weight: bold; border-radius: 5px; cursor: pointer; }\r\n");
      out.write("        .btn-del { color: red; text-decoration: none; font-weight: bold; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <h2 style=\"text-align:center; width:100%;\">📍 Route Manager: ");
      out.print( t.getTrainName() );
      out.write("</h2>\r\n");
      out.write("    <div style=\"text-align:center; margin-bottom:20px;\">\r\n");
      out.write("        <a href=\"ManageTrainServlet\" style=\"color:#667eea; text-decoration:none;\">← Back to Train List</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"route-box\">\r\n");
      out.write("            <h3>Current Stops</h3>\r\n");
      out.write("            <table>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>Station Name</th>\r\n");
      out.write("                    <th>Distance (km)</th>\r\n");
      out.write("                    <th>Action</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("                ");
 for(StationStop s : stops) { 
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>");
      out.print( s.getStationName() );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( s.getKmFromSource() );
      out.write(" km</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <a href=\"ManageRouteServlet?action=delete&distId=");
      out.print( s.getDistanceId() );
      out.write("&trainId=");
      out.print( t.getTrainId() );
      out.write("\" \r\n");
      out.write("                           onclick=\"return confirm('Remove this stop?')\" class=\"btn-del\">× Remove</a>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"add-box\">\r\n");
      out.write("            <h3>➕ Add New Stop</h3>\r\n");
      out.write("            <form action=\"ManageRouteServlet\" method=\"post\">\r\n");
      out.write("                <input type=\"hidden\" name=\"trainId\" value=\"");
      out.print( t.getTrainId() );
      out.write("\">\r\n");
      out.write("                \r\n");
      out.write("                <label>Station Name</label>\r\n");
      out.write("                <input type=\"text\" name=\"stationName\" placeholder=\"Ex: Kanpur\" required>\r\n");
      out.write("                \r\n");
      out.write("                <label>Distance from Source (km)</label>\r\n");
      out.write("                <input type=\"number\" name=\"km\" placeholder=\"Ex: 850\" required>\r\n");
      out.write("                \r\n");
      out.write("                <button type=\"submit\" class=\"btn-add\">Add Station</button>\r\n");
      out.write("            </form>\r\n");
      out.write("            <p style=\"font-size:12px; color:grey; margin-top:10px;\">\r\n");
      out.write("                *Ensure the distance is correct relative to the Source (0km).\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
