/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.112
 * Generated at: 2025-12-09 15:10:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.railway.dao.ReservationDAO;
import com.railway.model.Reservation;
import com.railway.model.User;

public final class my_002dbookings_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("com.railway.model.Reservation");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.railway.model.User");
    _jspx_imports_classes.add("com.railway.dao.ReservationDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    // 1. Security Check: Is user logged in?
    User user = (User) session.getAttribute("user");
    if(user == null) { 
        response.sendRedirect("login.jsp"); 
        return; 
    }

    // 2. Fetch Data: Get bookings for this specific user
    ReservationDAO dao = new ReservationDAO();
    List<Reservation> myBookings = dao.getUserReservations(user.getUserId());

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>My Bookings - Railway System</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body { font-family: 'Segoe UI', sans-serif; background: #f7fafc; padding: 20px; }\r\n");
      out.write("        .container { max-width: 900px; margin: 0 auto; }\r\n");
      out.write("        \r\n");
      out.write("        /* Header Style */\r\n");
      out.write("        .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 30px; }\r\n");
      out.write("        .header h2 { color: #2d3748; margin: 0; }\r\n");
      out.write("        .btn-back { text-decoration: none; color: #667eea; font-weight: bold; padding: 8px 15px; border: 1px solid #667eea; border-radius: 5px; transition: 0.3s; }\r\n");
      out.write("        .btn-back:hover { background: #667eea; color: white; }\r\n");
      out.write("\r\n");
      out.write("        /* Ticket Card Style */\r\n");
      out.write("        .ticket-card { background: white; border-radius: 10px; padding: 20px; box-shadow: 0 4px 6px rgba(0,0,0,0.05); margin-bottom: 20px; display: flex; justify-content: space-between; align-items: center; border-left: 5px solid #667eea; transition: 0.3s; }\r\n");
      out.write("        .ticket-card:hover { transform: translateY(-3px); box-shadow: 0 10px 15px rgba(0,0,0,0.1); }\r\n");
      out.write("        \r\n");
      out.write("        .ticket-info h3 { margin: 0 0 5px 0; color: #2d3748; }\r\n");
      out.write("        .ticket-route { color: #718096; font-size: 14px; margin-bottom: 10px; }\r\n");
      out.write("        .ticket-details { font-size: 14px; color: #4a5568; display: flex; gap: 20px; }\r\n");
      out.write("        .ticket-details span { background: #edf2f7; padding: 5px 10px; border-radius: 5px; }\r\n");
      out.write("\r\n");
      out.write("        .ticket-status { text-align: right; }\r\n");
      out.write("        .price { font-size: 20px; font-weight: bold; color: #2d3748; }\r\n");
      out.write("        .status-badge { display: inline-block; padding: 5px 12px; border-radius: 20px; font-size: 12px; font-weight: bold; margin-top: 5px; }\r\n");
      out.write("        \r\n");
      out.write("        .status-confirmed { background: #c6f6d5; color: #276749; }\r\n");
      out.write("        .status-cancelled { background: #fed7d7; color: #9b2c2c; }\r\n");
      out.write("        \r\n");
      out.write("        .no-bookings { text-align: center; margin-top: 50px; color: #a0aec0; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("            <h2>🎟️ My Bookings</h2>\r\n");
      out.write("            <a href=\"user-dashboard.jsp\" class=\"btn-back\">← Back to Dashboard</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");
 
        if (myBookings != null && !myBookings.isEmpty()) {
            for (Reservation r : myBookings) {
        
      out.write("\r\n");
      out.write("            <div class=\"ticket-card\">\r\n");
      out.write("                <div class=\"ticket-info\">\r\n");
      out.write("                    <h3>");
      out.print( r.getTrainName() );
      out.write(' ');
      out.write('(');
      out.print( r.getTrainNumber() );
      out.write(")</h3>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"ticket-route\">\r\n");
      out.write("                        ");
      out.print( r.getSourceStation() );
      out.write(' ');
      out.write('➝');
      out.write(' ');
      out.print( r.getDestinationStation() );
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"ticket-details\">\r\n");
      out.write("                        <span>📅 ");
      out.print( r.getJourneyDate() );
      out.write("</span>\r\n");
      out.write("                        <span>👤 ");
      out.print( r.getPassengerName() );
      out.write("</span>\r\n");
      out.write("                        <span>💺 Seats: ");
      out.print( r.getSeatsBooked() );
      out.write("</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"ticket-status\">\r\n");
      out.write("			    <div class=\"price\">₹");
      out.print( r.getTotalFare() );
      out.write("</div>\r\n");
      out.write("			\r\n");
      out.write("			    ");
 
			        // 🧠 LOGIC: Check Date vs Today
			        java.util.Date today = new java.util.Date();
			        boolean isPastJourney = r.getJourneyDate().before(today);
			        boolean isCancelled = "CANCELLED".equalsIgnoreCase(r.getBookingStatus());
			    
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			    ");
 if (isCancelled) { 
      out.write("\r\n");
      out.write("			        <span class=\"status-badge status-cancelled\">CANCELLED</span>\r\n");
      out.write("			    \r\n");
      out.write("			    ");
 } else if (isPastJourney) { 
      out.write("\r\n");
      out.write("			        <span class=\"status-badge\" style=\"background:#e2e8f0; color:#4a5568;\">JOURNEY COMPLETED</span>\r\n");
      out.write("			        <br>\r\n");
      out.write("			        <span style=\"font-size:10px; color:grey;\">(History)</span>\r\n");
      out.write("			\r\n");
      out.write("			    ");
 } else { 
      out.write("\r\n");
      out.write("			        <span class=\"status-badge status-confirmed\">CONFIRMED</span>\r\n");
      out.write("			        <br><br>\r\n");
      out.write("			        \r\n");
      out.write("			        <a href=\"view-ticket.jsp?id=");
      out.print( r.getReservationId() );
      out.write("\" target=\"_blank\" \r\n");
      out.write("			           style=\"color: blue; text-decoration: underline; font-size: 13px; margin-right: 10px;\">\r\n");
      out.write("			           ⬇ Download\r\n");
      out.write("			        </a>\r\n");
      out.write("			\r\n");
      out.write("			        <a href=\"CancelServlet?id=");
      out.print( r.getReservationId() );
      out.write("\" \r\n");
      out.write("			           onclick=\"return confirm('Are you sure you want to cancel? Refund will be processed.')\"\r\n");
      out.write("			           style=\"background: #e53e3e; color: white; padding: 5px 10px; border-radius: 4px; text-decoration: none; font-size: 12px;\">\r\n");
      out.write("			           ✖ Cancel\r\n");
      out.write("			        </a>\r\n");
      out.write("			    ");
 } 
      out.write("\r\n");
      out.write("			    \r\n");
      out.write("			    <br><br>\r\n");
      out.write("			    <small style=\"color: #718096;\">ID: #");
      out.print( r.getReservationId() );
      out.write("</small>\r\n");
      out.write("			</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 
            }
        } else { 
        
      out.write("\r\n");
      out.write("            <div class=\"no-bookings\">\r\n");
      out.write("                <h3>You haven't booked any tickets yet.</h3>\r\n");
      out.write("                <p>Go to the dashboard to find trains!</p>\r\n");
      out.write("                <a href=\"search-trains.jsp\" class=\"btn-back\">Book a Ticket</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
