/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.112
 * Generated at: 2025-12-10 12:33:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import java.util.ArrayList;
import com.railway.model.Train;

public final class search_002dresults_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.railway.model.Train");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Search Results</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        body { font-family: 'Segoe UI', sans-serif; background: #f7fafc; padding: 30px; }\r\n");
      out.write("        .container { max-width: 1000px; margin: 0 auto; }\r\n");
      out.write("        \r\n");
      out.write("        /* Header */\r\n");
      out.write("        .header { margin-bottom: 30px; text-align: center; }\r\n");
      out.write("        .header h2 { color: #2d3748; margin: 0; }\r\n");
      out.write("        .sub-header { color: #718096; margin-top: 5px; }\r\n");
      out.write("        \r\n");
      out.write("        /* Train Card */\r\n");
      out.write("        .train-card { \r\n");
      out.write("            background: white; \r\n");
      out.write("            padding: 25px; \r\n");
      out.write("            border-radius: 12px; \r\n");
      out.write("            box-shadow: 0 4px 10px rgba(0,0,0,0.05); \r\n");
      out.write("            margin-bottom: 25px; \r\n");
      out.write("            display: flex; \r\n");
      out.write("            justify-content: space-between; \r\n");
      out.write("            align-items: center; \r\n");
      out.write("            border-left: 6px solid #667eea; \r\n");
      out.write("            transition: 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        .train-card:hover { transform: translateY(-3px); box-shadow: 0 10px 20px rgba(0,0,0,0.1); }\r\n");
      out.write("\r\n");
      out.write("        /* Left Section: Train Info */\r\n");
      out.write("        .train-info { flex: 2; }\r\n");
      out.write("        .train-name { font-size: 20px; font-weight: bold; color: #2d3748; }\r\n");
      out.write("        .train-number { background: #edf2f7; padding: 2px 8px; border-radius: 4px; font-size: 14px; color: #4a5568; margin-left: 10px; }\r\n");
      out.write("        \r\n");
      out.write("        /* The Journey Display (Source -> Dest) */\r\n");
      out.write("        .journey-route { font-size: 18px; font-weight: bold; color: #5a67d8; margin-top: 10px; display: flex; align-items: center; gap: 10px; }\r\n");
      out.write("        \r\n");
      out.write("        /* The \"In-Between\" Full Route display */\r\n");
      out.write("        .via-route { font-size: 13px; color: #718096; margin-top: 5px; background: #fff5f5; padding: 5px; border-radius: 4px; display: inline-block; }\r\n");
      out.write("        \r\n");
      out.write("        .train-time { font-weight: bold; color: #4a5568; margin-top: 10px; font-size: 14px; }\r\n");
      out.write("        .distance-badge { background: #fefcbf; color: #744210; padding: 3px 8px; border-radius: 10px; font-size: 12px; font-weight: bold; margin-left: 10px; }\r\n");
      out.write("\r\n");
      out.write("        /* Right Section: Booking */\r\n");
      out.write("        .booking-section { flex: 1; text-align: right; border-left: 1px solid #eee; padding-left: 20px; }\r\n");
      out.write("        .seat-green { color: #38a169; font-weight: bold; font-size: 14px; margin-bottom: 10px; display: block; }\r\n");
      out.write("        .seat-red { color: #e53e3e; font-weight: bold; }\r\n");
      out.write("        \r\n");
      out.write("        select { padding: 8px; border-radius: 5px; border: 1px solid #cbd5e0; width: 100%; margin-bottom: 10px; }\r\n");
      out.write("        .btn-book { width: 100%; padding: 10px; background: #48bb78; color: white; border: none; border-radius: 5px; font-weight: bold; cursor: pointer; transition: 0.2s; }\r\n");
      out.write("        .btn-book:hover { background: #38a169; }\r\n");
      out.write("        \r\n");
      out.write("        .no-results { text-align: center; margin-top: 50px; color: #718096; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("            <h2>🚄 ");
      out.print( request.getAttribute("source") );
      out.write(' ');
      out.write('➝');
      out.write(' ');
      out.print( request.getAttribute("destination") );
      out.write("</h2>\r\n");
      out.write("            <div class=\"sub-header\">Journey Date: ");
      out.print( request.getAttribute("journeyDate") );
      out.write("</div>\r\n");
      out.write("            <br>\r\n");
      out.write("            <a href=\"search-trains.jsp\" style=\"text-decoration:none; color:#667eea; font-weight:bold;\">← New Search</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");
 
            List<Train> trains = (List<Train>) request.getAttribute("trainList");
            String journeyDate = (String) request.getAttribute("journeyDate");
            
            // Search Parameters
            String searchSource = (String) request.getAttribute("source");
            String searchDest = (String) request.getAttribute("destination");

            if (trains != null && !trains.isEmpty()) {
                for (Train t : trains) {
        
      out.write("\r\n");
      out.write("            <div class=\"train-card\">\r\n");
      out.write("                <div class=\"train-info\">\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <span class=\"train-name\">");
      out.print( t.getTrainName() );
      out.write("</span>\r\n");
      out.write("                        <span class=\"train-number\">");
      out.print( t.getTrainNumber() );
      out.write("</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"journey-route\">\r\n");
      out.write("                        ");
      out.print( searchSource );
      out.write(' ');
      out.write('➝');
      out.write(' ');
      out.print( searchDest );
      out.write("\r\n");
      out.write("                        <span class=\"distance-badge\">📍 ");
      out.print( t.getJourneyDistance() );
      out.write(" km</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"via-route\">\r\n");
      out.write("                        <strong>Full Route:</strong> ");
      out.print( t.getViaStations() );
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"train-time\">\r\n");
      out.write("                        🕒 Dep: ");
      out.print( t.getDepartureTime() );
      out.write(" | Arr: ");
      out.print( t.getArrivalTime() );
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"booking-section\">\r\n");
      out.write("                    ");
 if(t.getAvailableSeats() > 0) { 
      out.write("\r\n");
      out.write("                        <span class=\"seat-green\">✔ ");
      out.print( t.getAvailableSeats() );
      out.write(" Seats Available</span>\r\n");
      out.write("                        \r\n");
      out.write("                        <form action=\"book-ticket.jsp\" method=\"get\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"trainId\" value=\"");
      out.print( t.getTrainId() );
      out.write("\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"date\" value=\"");
      out.print( journeyDate );
      out.write("\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"source\" value=\"");
      out.print( searchSource );
      out.write("\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"destination\" value=\"");
      out.print( searchDest );
      out.write("\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"distance\" value=\"");
      out.print( t.getJourneyDistance() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("                            <select name=\"trainClass\">\r\n");
      out.write("                                <option value=\"GN\">General</option>\r\n");
      out.write("                                <option value=\"SL\">Sleeper</option>\r\n");
      out.write("                                <option value=\"3AC\">3rd AC</option>\r\n");
      out.write("                                <option value=\"2AC\">2nd AC</option>\r\n");
      out.write("                                <option value=\"1AC\">1st AC</option>\r\n");
      out.write("                            </select>\r\n");
      out.write("                            \r\n");
      out.write("                            <button type=\"submit\" class=\"btn-book\">Book Now</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("\r\n");
      out.write("                    ");
 } else { 
      out.write("\r\n");
      out.write("                        <span class=\"seat-red\">❌ SOLD OUT</span>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 
                }
            } else { 
        
      out.write("\r\n");
      out.write("            <div class=\"no-results\">\r\n");
      out.write("                <h3>😕 No trains found directly connecting these stations.</h3>\r\n");
      out.write("                <p>Try searching for major stations like \"Kolkata\" or \"Delhi\".</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
