/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.112
 * Generated at: 2025-12-09 13:41:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.railway.dao.ReservationDAO;
import com.railway.model.Reservation;
import com.railway.model.User;
import java.util.List;

public final class view_002dticket_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("com.railway.model.Reservation");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.railway.model.User");
    _jspx_imports_classes.add("com.railway.dao.ReservationDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    // 1. Security Check
    User user = (User) session.getAttribute("user");
    if(user == null) { response.sendRedirect("login.jsp"); return; }

    // 2. Get the Reservation ID from the URL link (e.g. view-ticket.jsp?id=5)
    String idStr = request.getParameter("id");
    if(idStr == null) { response.sendRedirect("my-bookings.jsp"); return; }
    
    int resId = Integer.parseInt(idStr);

    // 3. Fetch the specific reservation from Database
    ReservationDAO dao = new ReservationDAO();
    // We reuse the existing method to get all bookings, then find the specific one
    // (In a real app, you would make a getReservationById() method in DAO, but this works for now)
    List<Reservation> list = dao.getUserReservations(user.getUserId());
    
    Reservation res = null;
    for(Reservation r : list) {
        if(r.getReservationId() == resId) {
            res = r;
            break;
        }
    }

    if(res == null) { 
        out.println("<h3>Ticket not found or access denied.</h3>"); 
        return; 
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Ticket #");
      out.print( res.getReservationId() );
      out.write("</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Same Styling as Booking Success */\r\n");
      out.write("        body { font-family: 'Courier New', Courier, monospace; background: white; display: flex; flex-direction: column; align-items: center; padding-top: 50px; }\r\n");
      out.write("        .ticket { background: white; width: 600px; padding: 20px; border: 2px solid #2d3748; box-shadow: none; }\r\n");
      out.write("        .header { text-align: center; border-bottom: 2px dashed #000; padding-bottom: 10px; margin-bottom: 20px; }\r\n");
      out.write("        .header h2 { color: #000; margin: 0; }\r\n");
      out.write("        .success-msg { color: #000; font-weight: bold; font-size: 18px; }\r\n");
      out.write("        .row { display: flex; justify-content: space-between; margin-bottom: 15px; }\r\n");
      out.write("        .label { color: #555; font-size: 14px; font-weight: bold; }\r\n");
      out.write("        .value { color: #000; font-size: 16px; font-weight: bold; }\r\n");
      out.write("        .total-price { background: #eee; padding: 15px; text-align: center; border: 2px solid #000; font-size: 24px; font-weight: bold; color: #000; margin-top: 20px; }\r\n");
      out.write("        \r\n");
      out.write("        /* Hide buttons when printing */\r\n");
      out.write("        @media print {\r\n");
      out.write("            .btn-print, .btn-close { display: none; }\r\n");
      out.write("            body { padding-top: 0; }\r\n");
      out.write("            .ticket { border: 2px solid black; width: 100%; max-width: 100%; }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-print { background: #2d3748; color: white; padding: 10px 20px; border: none; cursor: pointer; font-size: 16px; margin-top: 20px; }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"ticket\">\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("            <h2>🚂 INDIAN RAILWAYS</h2>\r\n");
      out.write("            <p class=\"success-msg\">E-TICKET RESERVATION SLIP</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <span class=\"label\">TRAIN</span><br>\r\n");
      out.write("                <span class=\"value\">");
      out.print( res.getTrainName() );
      out.write(' ');
      out.write('(');
      out.print( res.getTrainNumber() );
      out.write(")</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                 <span class=\"label\">PNR / ID</span><br>\r\n");
      out.write("                 <span class=\"value\">#");
      out.print( res.getReservationId() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <span class=\"label\">ROUTE</span><br>\r\n");
      out.write("                <span class=\"value\">");
      out.print( res.getSourceStation() );
      out.write(' ');
      out.write('➝');
      out.write(' ');
      out.print( res.getDestinationStation() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <span class=\"label\">PASSENGER</span><br>\r\n");
      out.write("                <span class=\"value\">");
      out.print( res.getPassengerName() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <span class=\"label\">AGE / GENDER</span><br>\r\n");
      out.write("                <span class=\"value\">");
      out.print( res.getAge() );
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.print( res.getGender() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <span class=\"label\">JOURNEY DATE</span><br>\r\n");
      out.write("                <span class=\"value\">");
      out.print( res.getJourneyDate() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <span class=\"label\">SEATS</span><br>\r\n");
      out.write("                <span class=\"value\">");
      out.print( res.getSeatsBooked() );
      out.write("</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("             <div>\r\n");
      out.write("                <span class=\"label\">STATUS</span><br>\r\n");
      out.write("                <span class=\"value\">CONFIRMED</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"total-price\">\r\n");
      out.write("            TOTAL PAID: ₹");
      out.print( res.getTotalFare() );
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div style=\"text-align: center;\">\r\n");
      out.write("        <button onclick=\"window.print()\" class=\"btn-print\">🖨️ Print / Save as PDF</button>\r\n");
      out.write("        <br><br>\r\n");
      out.write("        <a href=\"my-bookings.jsp\" class=\"btn-close\" style=\"color: blue;\">Close</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
